language: csharp
mono: none
solution: .\reqparser.sln
dotnet: 2.2
jobs: 
  include: 
  - stage: build
    script:
     - dotnet restore 
     - dotnet build
  - stage: test
    script:
     - dotnet test